[env]
platform = espressif32
board = esp32dev
framework = arduino
#upload_port = /dev/cu.usbserial-017FEB09
#monitor_port = /dev/cu.usbserial-017FEB09
upload_port = /dev/cu.usbserial-0001
monitor_port = /dev/cu.usbserial-0001
monitor_speed = 115200
board_build.filesystem = spiffs
platform_packages = 
    tool-esptoolpy@~1.40501.0

[env:updater]
board_build.partitions = updater_partitions.csv
extra_scripts = post:copy_binaries.py
build_src_filter = +<updater.cpp> -<main.cpp> -<bt_audio.cpp> -<noise_gen.cpp> -<web_server.cpp> -<storage.cpp>
lib_deps = 
	bblanchon/ArduinoJson @ ^7.2.0

[env:app]
board_build.partitions = app_partitions.csv
board_upload.offset_address = 0x100000
extra_scripts = 
	post:copy_binaries.py
build_src_filter = +<main.cpp> +<bt_audio.cpp> +<noise_gen.cpp> +<web_server.cpp> +<storage.cpp> -<updater.cpp>
lib_deps = 
	tzapu/WiFiManager @ ^2.0.17
	earlephilhower/ESP8266Audio @ ^1.9.7
	bblanchon/ArduinoJson @ ^7.2.0


build_flags = 
	-D CORE_DEBUG_LEVEL=4
	-D LOG_LOCAL_LEVEL=ESP_LOG_DEBUG
	-D CONFIG_ASYNC_TCP_STACK_SIZE=4096
	-D os_get_random=esp_random
	-Wno-cpp
	-Wno-deprecated-declarations
